### PR TITLE
feat: improve lp styling

### PR DESCRIPTION
**Pull request by TheKohan**
Hi !
I've spent some time on improving styling on the LP.
* added `tailwindcss` which makes styling bearable
* rewrote all `css modules` files to use tailwind
* ported some of the colors from `--ifm` variables to `tailwind.config.js`
* played around with styling generally.

There is still a bit work to do i suppose 😄 
Let me know what do you think. 

image

### CODE REVIEW

**Comment by TheKohan** [comment]
@grabbou, @ericvicenti - tell me what you think.

**Comment by ericvicenti** [comment]
this is exciting, it looks like a big improvement! I will try running it this weekend and will merge soon

**Comment by grabbou** [comment]
Unpopular opinion: I like Tailwind! So I support this move. Will make styling much easier!

**Review by grabbou — APPROVED** [review]

**Comment by TheKohan** [comment]
@grabbou not so unpopular anymore, i was once in "this thing bloats my beautiful markup" camp, but not anymore. Tailwind really made me like styling again 😄, I like how powerful it is when doing pseudo selector stuff.

**Comment by ericvicenti** [comment]
I'm not a big fan of tailwind but I love the improvements you've made.

Hope to see more improvements coming from you and the community soon!

**Pull request merged**
