### PR TITLE
feat: infer nested & lookup model keys

### PR DESCRIPTION
**Pull request by arpitBhalla**

### CODE REVIEW

**Comment by grabbou** [comment]
Thanks for the PR!

> In future, can improve the types to support params

What do you mean by this? Isn't this PR supporting params by expanding lookup into `<modelName>/${string}/...` as many times as the lookup is nested?

**Comment by arpitBhalla** [comment]
Yes, it does

I thought params would be an Object in future

**Comment by grabbou** [comment]
Ah, no! That was just my moment of stupidness! Paths are way to go! :fire:

**Review by grabbou — APPROVED** [review]
This is simply AWESOME! I hate those generics, spent so much time working on them last time... thanks! 🔥

**Pull request merged**
