### PR TITLE
[:refactoring] immutable-importedConnection

### PR DESCRIPTION
**Pull request by k70suK3-k06a7ash1**
Can someone please review this?

### CODE REVIEW

**Comment by grabbou** [comment]
Hey! Thanks for the PR. Could you please provide an explanation behind the changes? Thank you!

**Comment by k70suK3-k06a7ash1** [comment]
@grabbou 

Using an IIFE (Immediately Invoked Function Expression)  can enhance the readability and clarity of your code by grouping related functionality together in one place. This makes it easier to understand the purpose and scope of the code, as it is immediately clear what part of the code is executed right away and encapsulated.

Thank You!

**Comment by k70suK3-k06a7ash1** [comment]
And, Having a single return statement makes the rendered UI self-evident.

**Comment by grabbou** [comment]
I see. Thanks for providing further clarification. Unfortunately, while I definitely see your point, it is not in line with the guidelines that me and Eric apply when working on Rise. There are a lot of styling choices and this is the one we made. We invite you to contribute in the future and to discuss it with us on our Discord server. I would love to work on some bugs or features!

Once again, apologies for closing. I imagine this might not be what you expected, but we want to avoid style-only PRs, otherwise we would spend too much time reviewing them!

**Pull request closed without merging**
