### PR TITLE
fix: get started link style

### PR DESCRIPTION
**Pull request by adham618**
Server-Defined-Rendering-for-React-Native-Rise-Tools

### CODE REVIEW

**Comment by ericvicenti** [comment]
Thanks for the PR! Guess we didn't test this on firefox 😅

In the future it would be helpful to explain what browser you found the issue on.

**Comment by adham618** [comment]
@ericvicenti Chrome macbook

**Comment by ericvicenti** [comment]
Oh, huh! For me it looks fine right now on Safari and Chrome, but on Firefox the button is not aligned

**Comment by adham618** [comment]
This issue only occurs in older versions of browsers. After updating Chrome the problem disappeared

**Pull request merged**
